### PR TITLE
feat(bff): bff service has been implemented

### PR DESCRIPTION
**Pull request by serguntchik**
All tasks have been implemented, including all optional ones (NestJS and products list cache)

Products API: https://0efj4ykl5i.execute-api.eu-west-1.amazonaws.com/dev
Cart API: http://serguntchik-cart-api-dev.eu-west-1.elasticbeanstalk.com/api/profile
Bff API: https://dzpjptafi85kt.cloudfront.net

Products API with bff: https://dzpjptafi85kt.cloudfront.net/products
Cart API with bff: https://dzpjptafi85kt.cloudfront.net/cart

FE application: https://d23x533cdax2wv.cloudfront.net/
FE pull request: https://github.com/serguntchik/shop-frontend/pull/7

### CODE REVIEW

**Comment by noway36** [comment]
For some reason I don't see the message `Cannot process request` in the 502 response

**Comment by noway36** [comment]
Looks like you forgot about proper naming for the bff service 🙂 
`https://dzpjptafi85kt.cloudfront.net` -> `{yours_github_account_login}-bff-api-{environment_name}`
But for me it's fine

**Comment by noway36** [comment]
LGTM 7/7!

**Comment by serguntchik** [comment]
> Looks like you forgot about proper naming for the bff service 🙂 `https://dzpjptafi85kt.cloudfront.net` -> `{yours_github_account_login}-bff-api-{environment_name}` But for me it's fine

The bff uri is http://serguntchik-bff-api-dev.eu-west-1.elasticbeanstalk.com, as expected :) I've just put it behind cloudfront so that it's https instead of http, so that the users don't have to enable insecure content on their web-page :)

**Comment by serguntchik** [comment]
> For some reason I don't see the message `Cannot process request` in the 502 response

Fixed, thanks for noticing! :)

**Pull request merged**
